name: Deploy on Dev Merge to Master
on:
  push:
    branches:
      - master

jobs:
  update_local:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync to Local Path
        run: |
          Copy-Item -Path "./extension_folder/*" -Destination "H:\gator extention\places-api" -Recurse -Force
