name: Sync Extension Locally
on:
  push:
    branches:
      - main

jobs:
  update_local:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync to Local Path
        run: |
          cp -r ./extension_folder "H:\gator extention\places-api"
